"""Shared metadata constant sets used across analysis and editing."""

from __future__ import annotations

DATE_FIELD_KEYS = [
    "DateTimeOriginal",
    "CreateDate",
    "ModifyDate",
    "CreationDate",
    "ModDate",
    "Created",
    "Modified",
]

GPS_TAGS_TO_SPOOF = [
    "GPSLatitude",
    "GPSLongitude",
    "GPSAltitude",
    "GPSAltitudeRef",
    "GPSSpeed",
    "GPSSpeedRef",
    "GPSImgDirection",
    "GPSImgDirectionRef",
    "GPSDestBearing",
    "GPSDestBearingRef",
    "GPSHPositioningError",
    "GPSTimeStamp",
    "GPSDateStamp",
    "GPSDateTime",
    "GPSPosition",
]

DEVICE_TAGS_TO_CLEAR = [
    "Make",
    "Model",
    "Software",
    "LensModel",
    "LensID",
    "LensMake",
    "LensInfo",
    "LensSerialNumber",
    "CameraSerialNumber",
    "SerialNumber",
    "DeviceMfgDesc",
    "DeviceModelDesc",
    "ProfileCreator",
    "CreatorTool",
    "HostComputer",
    "UniqueCameraModel",
]

DATE_TAGS_TO_SPOOF = [
    "DateTimeOriginal",
    "CreateDate",
    "ModifyDate",
    "FileModifyDate",
    "FileCreateDate",
    "FileAccessDate",
    "DateCreated",
    "TimeCreated",
    "GPSDateStamp",
    "GPSTimeStamp",
    "GPSDateTime",
    "ProfileDateTime",
    "ProfileDateTimeOriginal",
    "MetadataDate",
    "DigitizedDate",
    "SubSecTimeOriginal",
    "SubSecTimeDigitized",
    "SubSecTime",
    "OffsetTime",
    "OffsetTimeOriginal",
    "OffsetTimeDigitized",
    "CreationDate",
    "ModDate",
    "Created",
    "Modified",
]

TIMEZONE_OFFSETS = [
    "+00:00",
    "+01:00",
    "+02:00",
    "+03:00",
    "+04:00",
    "+05:00",
    "+06:00",
    "+07:00",
    "+08:00",
    "+09:00",
    "+10:00",
    "-05:00",
    "-06:00",
    "-07:00",
    "-08:00",
]

OFFSET_TAGS = [
    "OffsetTime",
    "OffsetTimeOriginal",
    "OffsetTimeDigitized",
]

SUBSEC_TAGS = [
    "SubSecTime",
    "SubSecTimeOriginal",
    "SubSecTimeDigitized",
]

ICC_TAGS = {
    "ProfileDescription",
    "ProfileCopyright",
    "ProfileID",
    "ProfileCreator",
    "ProfileDateTime",
    "ProfileClass",
    "ColorSpaceData",
    "RenderingIntent",
    "ProfileVersion",
    "MeasurementObserver",
    "PrimaryPlatform",
    "DeviceManufacturer",
    "DeviceModel",
    "ProfileFileSignature",
    "CMMFlags",
    "ConnectionSpaceIlluminant",
    "ProfileConnectionSpace",
    "DisplayP3",
}

FILE_TECH_TAGS = {
    "FileSize",
    "FileType",
    "FileTypeExtension",
    "MIMEType",
    "FilePermissions",
    "Directory",
    "FileInodeChangeDate",
    "ThumbnailOffset",
    "ThumbnailLength",
    "ThumbnailImage",
    "PreviewImage",
    "ExifByteOrder",
}

CAMERA_TECH_TAGS = {
    "ImageWidth",
    "ImageHeight",
    "BitsPerSample",
    "Compression",
    "PhotometricInterpretation",
    "Orientation",
    "SamplesPerPixel",
    "XResolution",
    "YResolution",
    "ResolutionUnit",
    "ColorSpace",
    "ExifImageWidth",
    "ExifImageHeight",
    "EncodingProcess",
    "YCbCrSubSampling",
    "YCbCrPositioning",
    "Megapixels",
    "ImageSize",
    "ScaleFactor35efl",
    "ShutterSpeed",
    "Aperture",
    "LightValue",
    "FOV",
    "HyperfocalDistance",
    "DOF",
    "Flash",
    "MeteringMode",
    "ExposureProgram",
    "ExposureMode",
    "ExposureCompensation",
    "ExposureTime",
    "FNumber",
    "ISO",
    "FocalLength",
    "FocalLengthIn35mmFormat",
    "WhiteBalance",
    "DigitalZoomRatio",
    "SceneCaptureType",
    "Contrast",
    "Saturation",
    "Sharpness",
    "SubjectDistanceRange",
    "ComponentsConfiguration",
    "CompressedBitsPerPixel",
    "FlashpixVersion",
    "ExifVersion",
    "InteropIndex",
    "RelatedImageWidth",
    "RelatedImageHeight",
    "RunTimeSincePowerUp",
    "RunTimeFlags",
    "RunTimeValue",
    "RunTimeScale",
    "RunTimeEpoch",
    "CompositeImageExposureTimes",
    "GPSLatitudeRef",
    "GPSLongitudeRef",
    "OffsetTime",
    "OffsetTimeOriginal",
    "OffsetTimeDigitized",
    "SubSecTimeOriginal",
    "SubSecTimeDigitized",
    "SubSecTime",
}

TECHNICAL_TAGS = ICC_TAGS | FILE_TECH_TAGS | CAMERA_TECH_TAGS

SENSITIVE_KEYWORDS = [
    "GPS",
    "Author",
    "Creator",
    "Artist",
    "Owner",
    "Make",
    "Model",
    "SerialNumber",
    "CameraSerialNumber",
    "InternalSerialNumber",
    "OwnerName",
    "LensSerialNumber",
    "Software",
    "CreatorTool",
    "HostComputer",
    "Date",
    "Time",
    "Created",
    "Modified",
    "Copyright",
    "Comment",
    "UserComment",
    "Description",
    "Subject",
    "Title",
    "UniqueID",
    "ImageUniqueID",
    "RegionExtensions",
    "LensModel",
    "LensID",
]

SENSITIVE_EXACT_TAGS = {
    "Author",
    "Creator",
    "Artist",
    "Owner",
    "Make",
    "Model",
    "SerialNumber",
    "CameraSerialNumber",
    "InternalSerialNumber",
    "OwnerName",
    "LensSerialNumber",
    "Software",
    "CreatorTool",
    "HostComputer",
    "Copyright",
    "Comment",
    "UserComment",
    "Description",
    "Subject",
    "Title",
    "UniqueID",
    "ImageUniqueID",
    "LensModel",
    "LensID",
}

SENSITIVE_PARTIAL_TAGS = (
    "Date",
    "Time",
    "Created",
    "Modified",
    "RegionExtensions",
)

# Biometric / hardware fingerprint tags — remove only, never spoof.
ALWAYS_DELETE_TAGS: frozenset[str] = frozenset({
    "RegionExtensionsFaceID",
    "RegionExtensionsAngleInfoRoll",
    "RegionExtensionsAngleInfoYaw",
    "RegionExtensionsConfidenceLevel",
    "RegionAppliedToDimensionsH",
    "RegionAppliedToDimensionsW",
    "RegionAppliedToDimensionsUnit",
    "RegionAreaH",
    "RegionAreaW",
    "RegionAreaX",
    "RegionAreaY",
    "RegionAreaUnit",
    "RegionName",
    "RegionType",
    "RegionPersonDisplayName",
    "AccelerationVector",
    "MakerNoteVersion",
})

# Region* keys from new firmware may not be in ALWAYS_DELETE_TAGS yet.
ALWAYS_DELETE_PREFIXES: tuple[str, ...] = (
    "Region",
)

# Region children sit in nested XMP structs — -= on leaf tags fails; wipe parents.
REGION_XMP_NUKE_ARGS: tuple[str, ...] = (
    "-XMP:RegionInfo=",
    "-XMP-mwg-rs:Regions=",
    "-XMP:RegionAppliedToDimensions=",
    "-XMP:RegionAreaH=",
    "-XMP:RegionAreaW=",
    "-XMP:RegionAreaX=",
    "-XMP:RegionAreaY=",
    "-XMP:RegionExtensions=",
    "-XMP-mwg-rs:RegionExtensions=",
    "-XMP:RegionName=",
    "-XMP:RegionType=",
    "-XMP:RegionPersonDisplayName=",
    "-XMP-mwg-rs:RegionName=",
    "-XMP-mwg-rs:RegionType=",
    "-XMP-mwg-rs:RegionPersonDisplayName=",
)
